In [11]:
sentence = 新车买后发现主驾车门上有一个类似毛发物在漆面里，比漆面突出一点，摸上去有点隔手，有没有可能是出厂就是那样，还是有重新喷过漆求教 谢谢啦各位大师晚上好，换个2014款宏光1.5排量的尾牙总成 原装的 需要多少费用？怎样区别原厂与副厂的配件？请问IS300仪表盘上的ASF灯总是闪是怎么回事？保险在什么位置？气囊灯亮了怎么办

SyntaxError: invalid character in identifier (<ipython-input-11-b61372148122>, line 1)

In [10]:
tokens = sentence.split('|')

AttributeError: 'tuple' object has no attribute 'split'

In [5]:
tokens

['新车买后发现主驾车门上有一个类似毛发物在漆面里，比漆面突出一点，摸上去有点隔手，有没有可能是出厂就是那样，还是有重新喷过漆求教 谢谢啦各位大师晚上好，换个2014款宏光1.5排量的尾牙总成 原装的 需要多少费用？怎样区别原厂与副厂的配件？请问IS300仪表盘上的ASF灯总是闪是怎么回事？保险在什么位置？气囊灯亮了怎么办？']

In [12]:
a  = '101010101010'

In [13]:
a.count('0')

6

In [14]:
import tensorflow as tf

In [19]:
tf.zeros(3, 3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0])>

In [29]:
inputs = tf.ones([2, 20])

In [30]:
inputs

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]], dtype=float32)>

In [33]:
w1 = tf.keras.layers.Dense(inputs, 10)
w2 = tf.keras.layers.Dense(10)
V = tf.keras.layers.Dense(1)

TypeError: only size-1 arrays can be converted to Python scalars

In [24]:
w1.get_shape()

AttributeError: 'Dense' object has no attribute 'get_shape'